import type { Metadata } from "next";
// @ts-ignore: Cannot find module or type declarations for side-effect import of './globals.css'.
import "./globals.css";

export const metadata: Metadata = {
  title: "Rimba Kembali",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-poppins`}>{children}</body>
    </html>
  );
}
