import type { Metadata } from "next";
// @ts-ignore: Cannot find module or type declarations for side-effect import of './globals.css'.
import "./globals.css";
import Navbar from "@/components/partials/Navbar";
import Footer from "@/components/partials/Footer";
import { ToggleProvider, useToggle } from "@/context/ToggleContext";
import LoginModalWrapper from "@/components/ui/LoginModalWrapper";
import { ToastProvider } from "@/context/ToastProvider";
import { AuthProvider } from "@/context/AuthContext";
export const metadata: Metadata = {
  title: "Rimba Kembali",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-poppins bg-linear-to-b from-primary-50 to-primary-200`}
      >
        <AuthProvider>
          <ToastProvider>
            <ToggleProvider>
              <Navbar />
              <LoginModalWrapper />
              {children}
              <Footer logoSrc="/main-logo.svg" />
            </ToggleProvider>
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
